export const FoodActionTypes = {
  SET_DEFAULT_FOODS: "SET_DEFAULT_FOODS",
  GET_DEFAULT_FOODS: "GET_DEFAULT_FOODS",
  GET_SEARCHED_FOODS: "GET_SEARCHED_FOODS",
  SET_SEARCHED_FOODS: "SET_SEARCHED_FOODS",
};
